services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    restart: always
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080